// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY6SmQopx6JZGJVUE64L4K89tC9TxyX78',
    appId: '1:1003223150542:web:67bf29395721f1d89c859f',
    messagingSenderId: '1003223150542',
    projectId: 'undercoverclone-b8ecf',
    authDomain: 'undercoverclone-b8ecf.firebaseapp.com',
    databaseURL: 'https://undercoverclone-b8ecf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'undercoverclone-b8ecf.firebasestorage.app',
    measurementId: 'G-P0E7P0NW8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1rpKkGfMWh_kJj6G9QOIWsXe4Es1UU8',
    appId: '1:1003223150542:android:160fce32148c4b4c9c859f',
    messagingSenderId: '1003223150542',
    projectId: 'undercoverclone-b8ecf',
    databaseURL: 'https://undercoverclone-b8ecf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'undercoverclone-b8ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQcQbLGDONRJAh-YpkwXyoZGRL7Qh9Hc',
    appId: '1:1003223150542:ios:8bb028c10a829e429c859f',
    messagingSenderId: '1003223150542',
    projectId: 'undercoverclone-b8ecf',
    databaseURL: 'https://undercoverclone-b8ecf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'undercoverclone-b8ecf.firebasestorage.app',
    iosBundleId: 'com.example.undercoverGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTQcQbLGDONRJAh-YpkwXyoZGRL7Qh9Hc',
    appId: '1:1003223150542:ios:8bb028c10a829e429c859f',
    messagingSenderId: '1003223150542',
    projectId: 'undercoverclone-b8ecf',
    databaseURL: 'https://undercoverclone-b8ecf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'undercoverclone-b8ecf.firebasestorage.app',
    iosBundleId: 'com.example.undercoverGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY6SmQopx6JZGJVUE64L4K89tC9TxyX78',
    appId: '1:1003223150542:web:89bbb8177382c4b29c859f',
    messagingSenderId: '1003223150542',
    projectId: 'undercoverclone-b8ecf',
    authDomain: 'undercoverclone-b8ecf.firebaseapp.com',
    databaseURL: 'https://undercoverclone-b8ecf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'undercoverclone-b8ecf.firebasestorage.app',
    measurementId: 'G-DLEV0CHZZ1',
  );

}